name: "Deploy Node Application"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRETKEY: ${{ secrets.JWT_SECRETKEY }}
      NODE_ENV: ${{secrets.NODE_ENV}}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      CLIENT_SITE_URL: ${{secrets. CLIENT_SITE_URL}}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t shehanapareeth/ecommerce-node-backend .
      - name: Publish Image to docker hub
        run: docker push shehanapareeth/ecommerce-node-backend:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker  hub
        run: docker pull shehanapareeth/ecommerce-node-backend:latest
      - name: Remove existing container
        run: docker rm -f nodejs-app-container   
      - name: Run Docker Container
        run: docker run -p 5000:5000 --name nodejs-app-container -e MONGO_URI='${MONGO_URI}' -e JWT_SECRETKEY=${JWT_SECRETKEY} -e NODE_ENV=${NODE_ENV} -e STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY} -e CLIENT_SITE_URL=${CLIENT_SITE_URL} shehanapareeth/ecommerce-node-backend
      